# Generated by Django 2.2.16 on 2022-01-31 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20220131_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(help_text='Не более 1000 символов', max_length=1000, null=True, verbose_name='Текст комментария'),
        ),
    ]
