# Generated by Django 2.2.16 on 2022-05-31 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_auto_20220531_2109'),
        ('posts', '0011_auto_20220403_1132'),
    ]

    operations = [
    ]
